### PR TITLE
Use modular imports

### LINKED ISSUE #467: Remove references to HebrewCalendar
This is a followup of hebcal/hebcal-es6#475

I want to be able to call leyning APIs without bringing 150KB+ of Zmanim code into my bundle.

This means that, after I split APIs out of `HebrewCalendar`, I must migrate all references to `HebrewCalendar` in this repo.

This includes:

 - Change `HebrewCalendar.getSedra()` to call a standalone export (easy)
 - Handle `HebrewCalendar.getHolidaysOnDate()`; TBD based on hebcal/hebcal-es6#475
 - Optional, breaking change: Move `csv.ts` out of `index.ts`, so it's only imported if actually referenced.
    -  Tree shaking should drop it anyway, so this may not be necessary.
    - It would let me https://github.com/SLaks/tikkun.io/blob/calendar-rewrite-full/src/calendar-model/hacks.d.ts

### PR DESCRIPTION
**Pull request by SLaks**
Fixes #467 

**Warning**: This is a breaking change!  It removes `csv.ts` from `index.ts`.

With https://github.com/SLaks/tikkun.io/commit/894d3df687b85a07a1e63bee91f71556e4b150db, this actually works, except that `Locale` misses translations, AFAICT because `npm link` ends up with duplicate modules.

Once you release both packages on npm, I should be able to fully test.

### CODE REVIEW

**Comment by SLaks** [comment]
I verified that this works in my consuming app.

It should be ready to merge and release after you merge and release https://github.com/hebcal/hebcal-es6/pull/481, which this requires.

**Comment by SLaks** [comment]
Update: I'm having strange issues getting Jest to pass.

Update: I'm now getting errors from `@hebcal/leyning` tests as a result of this PR:

```ts
    SyntaxError: Unexpected token 'export'

    > 1 | import {HDate, months} from '@hebcal/core';
        | ^
      2 | import {getLeyningOnDate} from '../src/getLeyningOnDate';
      3 |
      4 | test('getLeyningOnDate-parsha', () => {

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1505:14)
      at Object.<anonymous> (node_modules/@hebcal/core/dist/index.cjs:7:16)
      at Object.require (test/getLeyningOnDate.spec.js:1:1)
```

It looks like the problem is that you can't `require()` a native ES module from `.cjs` when running under Jest (I believe this works fine in Rollup if you install `commonJs()`, but I didn't actually try that).

-----

I tried manually downgrading to `quick-lru@4`, but now I get different ES module errors:

```ts
    C:\Users\SSL\Development\Open-Source\Clones\hebcal-leyning\node_modules\@hebcal\core\dist\es\event.js:2
    import { HDate, Locale } from '@hebcal/hdate';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import {Event, flags} from '@hebcal/core/dist/es/event';
        | ^
      2 | import {Locale} from './locale';
      3 | import {calculateNumVerses, NUM_VERSES} from './common';
      4 | import {clone, cloneHaftara, sumVerses} from './clone';

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1505:14)
      at Object.require (src/getLeyningForHoliday.ts:1:1)
      at Object.require (src/csv.ts:4:1)
      at Object.require (test/csv.spec.js:12:1)
```

It looks like the problem here is that Jest treats extensionless imports as CommonJS rather than ESM, but I haven't found a way to fix that yet.  `extensionsToTreatAsEsm: ['.', '.ts'],` doesn't help

**Comment by SLaks** [comment]
Switching to vitest is probably the simplest fix; WDYT? https://stackoverflow.com/a/77398467/34397

**Comment by mjradwin** [comment]
Yes, I see the same problem. This worked just fine before because we rolled up quick-lru into index.cjs instead of having it as an external dependency. Could we have quick-lru as an external dependency for the esm version, but have it rolled into the release for index.cjs?

**Comment by mjradwin** [comment]
> Switching to vitest is probably the simplest fix; WDYT? https://stackoverflow.com/a/77398467/34397

I'm not inclined to switch from jest to vitest. I'd prefer to get the packaging correct instead.

There are other problems with not rolling up quick-lru inside of @hebcal/core's index.cjs. Consider this, which used to work fine before your changes to rollup config:

```
Welcome to Node.js v20.18.0.
Type ".help" for more information.
> const {HDate} = require('@hebcal/core');
/root/dev/hebcal-web/node_modules/@hebcal/core/dist/index.cjs:7
var QuickLRU = require('quick-lru');
               ^
Uncaught:
Error [ERR_REQUIRE_ESM]: require() of ES Module /root/dev/hebcal-web/node_modules/@hebcal/core/node_modules/quick-lru/index.js from /root/dev/hebcal-web/node_modules/@hebcal/core/dist/index.cjs not supported.
Instead change the require of index.js in /root/dev/hebcal-web/node_modules/@hebcal/core/dist/index.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/root/dev/hebcal-web/node_modules/@hebcal/core/dist/index.cjs:7:16) {
  code: 'ERR_REQUIRE_ESM'
}
> 
```

versus the esm version which does work fine with your rollup changes:

```
Welcome to Node.js v20.18.0.
Type ".help" for more information.
> const {HDate} = await import('@hebcal/core');
undefined
> new HDate()
HDate { yy: 5785, mm: 8, dd: 5, rd: 739196 }
```

**Comment by SLaks** [comment]
> Could we have quick-lru as an external dependency for the esm version, but have it rolled into the release for index.cjs?

LG

I don't really care about the cjs; it cannot support tree shaking anyway, so there is no real point in trying to keep it small.

**Comment by mjradwin** [comment]
OK, I pushed @hebcal/core 5.7.4 which fixes these jest errors by fixing index.cjs

https://github.com/hebcal/hebcal-es6/commit/23c29972c2b686bf90be7bfab0eb704a3cf678bb

**Comment by SLaks** [comment]
Embedding `quick-lru` in the CJS fixes most of the tests, but I still get

```ts
    C:\Users\SSL\Development\Open-Source\Clones\hebcal-es6\node_modules\quick-lru\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export default class QuickLRU extends Map {
                                                                                      ^^^^^^

    SyntaxError: Unexpected token 'export'

       8 | import { YomKippurKatanEvent } from './YomKippurKatanEvent.js';
       9 | import { HolidayEvent, RoshHashanaEvent, AsaraBTevetEvent, RoshChodeshEvent } from './HolidayEvent.js';
    > 10 |
         | ^
      11 | /*
      12 |     Hebcal - A Jewish Calendar Generator
      13 |     Copyright (c) 1994-2020 Danny Sadinoff

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1505:14)
      at Object.<anonymous> (../hebcal-es6/dist/es/holidays.js:10:40)
      at Object.require (src/specialReadings.ts:8:1)
      at Object.require (src/leyning.ts:7:1)
      at Object.require (src/getLeyningOnDate.ts:8:1)
      at Object.require (test/getLeyningOnDate.spec.js:2:1)
```

I'm not sure why `import QuickLRU from 'quick-lru';` fails where `import { months, HDate } from '@hebcal/hdate';` (the previous line from `hebcal-es6/dist/es/holidays.js`) succeeds

**Comment by mjradwin** [comment]
Part of the 5.7.3 was also renaming from dist/es to dist/esm to be consistent with @hebcal/hdate per your suggestion. I still see dist/es in that error message. Do you need to nuke your dist/ directory and build clean?

**Comment by SLaks** [comment]
I tried it locally, before you released.

**Comment by mjradwin** [comment]
> I'm not sure why `import QuickLRU from 'quick-lru';` fails where `import { months, HDate } from '@hebcal/hdate';` (the previous line from `hebcal-es6/dist/es/holidays.js`) succeeds

I can't reproduce this on macOS or Linux. What do you suggest?

**Comment by SLaks** [comment]
If you can get the tests to pass, go ahead and release.

Worst case, I'll send another PR

**Comment by SLaks** [comment]
This now works locally after installing quick-lru v4 in core (see my other PR)

**Comment by mjradwin** [comment]
Hmmm. This didn't seem to help. I'm now getting the same errors on macOS. Flummoxed.

**Comment by SLaks** [comment]
Confusingly, it passes with `npm link ..\hebcal-es6\`, but fails with `npx install-local ..\hebcal-es6\` or when installing the released version

**Comment by SLaks** [comment]
I fixed it!

You can probably revert https://github.com/hebcal/hebcal-es6/pull/484 if you want; I didn't try that

**Comment by SLaks** [comment]
(I debugged into the Jest loader to see what was going wrong)

**Comment by mjradwin** [comment]
Amazing. Merged in, and will release tomorrow

**Comment by mjradwin** [comment]
> Switching to vitest is probably the simplest fix; WDYT? https://stackoverflow.com/a/77398467/34397

After spending the past few days struggling with jest (after removing CommonJS), I'm convinced now that Vitest is in fact a better option. Over time will look to move things from Jest to Vitest (or for the repos that don't have TypeScript, possibly even using the built-in node:test which arrived ~3 years ago in Node 18.0)

**Pull request merged**
